SequenceRoot:

<SequenceRoot>:
    MainMenuSelect

<MainMenuSelect>:
    BoxLayout:
        orientation: "vertical"
        AnchorLayout:
            anchor_x: 'center'
            Label:
                text: "The Spectacular Sequence Selector"
                font_size: 120
        AnchorLayout:
            anchor_x: 'center'
            Button:
                text: "PLAY!"
                font_size: 120
                size_hint: (None,None)
                size: self.texture_size
                on_press: app.root.showNameForm()
        AnchorLayout:
            anchor_x: 'center'
            Button:
                text: "High Scores"
                font_size: 120
                size_hint: (None,None)
                size: self.texture_size
                on_press: app.root.showLeaderboard()

<InputNameForm>:
    nameInput:inputBox
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Choose a name!"
            font_size: 80
        Label:
            text: "It must be 3 letters or fewer"
            font_size: 80
        BoxLayout:
            AnchorLayout:
                anchor_y: 'center'
                TextInput:
                    id: inputBox
                    size_hint_y: None
                    height: self.minimum_height
                    font_size: 200
            AnchorLayout:
                anchor_y: 'center'
                Button:
                    text: "Continue"
                    font_size: 120
                    size_hint: (None,None)
                    size: self.texture_size
                    on_press: root.recordName()

<LeaderboardPage>:
    listScores:scoreList
    on_parent: self.displayScores()
    FloatLayout:
        Button:
            text: "Main Menu"
            font_size: 60
            size_hint: (None, None) 
            size: self.texture_size
            pos_hint: {'x': 0, 'top': 1}
            on_press: app.root.showHome()
        BoxLayout:
            orientation: "vertical"
            Label:
                text: "Top Scores:"
                font_size: 120
            RecycleView:
                id: scoreList
                viewclass: 'Label'   
                scroll_type: ['bars', 'content']
                scroll_wheel_distance: 20
                RecycleBoxLayout:
                    font_size: 80
                    default_size: None, dp(80)
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
                    spacing: dp(10)
        
<RulesPage>:
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "GAME RULES"
            font_size: 120
        Label:
            text: "- The game will take 50 seconds."
            font_size: 80
        Label:
            text: "- If time runs out you lose!"
            font_size: 80
        Label:
            text: "- If you beat 4 levels before the time runs out you win!"
            font_size: 80
        Label:
            text: "- You must rank all items from smallest to largest."
            font_size: 80
        Button:
            text: "CONTINUE"
            font_size: 120
            on_press: app.root.showSequenceGame()

<SequenceGame>:
    timerLabel: timerLbl
    buttonCountLabel: btnCountLbl
    buttonContainer: btnContainer
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: self.minimum_height
            Label:
                font_size: 60
                size_hint_y: None
                height: 80 
                text: "Score:"
            Label:
                id: timerLbl
                font_size: 60
                size_hint_y: None
                height: 80 
                text: "50"
            Label:
                font_size: 60
                size_hint_y: None
                height: 80 
                text: "Progress:"
            Label:
                id: btnCountLbl
                font_size: 60
                size_hint_y: None
                height: 80 
                text: "0"
        FloatLayout:
            id: btnContainer
            Button:
                text: "Btn 1"
                font_size: 60
                size_hint: (0.15, 0.1)
                on_press: root.sequenceButton(5)
            Button:
                text: "Btn 2"
                font_size: 60
                size_hint: (0.15, 0.1)
                on_press: root.sequenceButton(4)
            Button:
                text: "Btn 3"
                font_size: 60
                size_hint: (0.15, 0.1)
                on_press: root.sequenceButton(3)
            Button:
                text: "Btn 4"
                font_size: 60
                size_hint: (0.15, 0.1)
                on_press: root.sequenceButton(2)
            Button:
                text: "Btn 5"
                font_size: 60
                size_hint: (0.15, 0.1)
                on_press: root.sequenceButton(1)

<FailPage>:
    FloatLayout:
        Label:
            text: "Time over! you lose!"
            font_size: 120
        Button:
            text: "Main Menu"
            font_size: 60
            size_hint: (None, None) 
            size: self.texture_size
            pos_hint: {'x': 0, 'top': 1}
            on_press: app.root.showHome()

<SuccessPage>:
    winnerMessage: winnerMsg
    FloatLayout:
        BoxLayout:
            orientation: 'vertical'
            Label:
                text: "You win!"
                font_size: 120
            Label:
                id: winnerMsg
                text: "(username) your score was (score)"
                font_size: 80
        Button:
            text: "Main Menu"
            font_size: 60
            size_hint: (None, None) 
            size: self.texture_size
            pos_hint: {'x': 0, 'top': 1}
            on_press: app.root.showHome()